modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Double%20Doors"
logoFile="icon.png"

[[mods]]
modId="doubledoors"
version="5.5"
displayName="Double Doors"
displayURL="https://serilum.com/mod/double-doors"
authors="Rick South"
description='''Adds the ability for identical double doors, trapdoors and fence gates to be opened simultaneously via click or pressure plates and buttons.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, BirdieMiner, Cherriesaurus, Jack, Jeremy Langford, Michael W. S., pepe1191, Shana Gitnick, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.doubledoors]]
    modId="collective"
    type="required"
    versionRange="[7.53,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.doubledoors]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.5]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "doubledoors.mixins.json"